# Skill Conductor Pipeline Configuration
# Defines phases, skill mappings, and named workflows.

phases:
  explore:
    order: 10
    description: Understand the problem space
  shape:
    order: 20
    description: Define requirements and solution approaches
  plan:
    order: 30
    description: Create implementation plan
  build:
    order: 40
    description: Implement the solution
  verify:
    order: 50
    description: Verify correctness and quality
  review:
    order: 60
    description: Independent review
  finish:
    order: 70
    description: Integrate and ship

skills:
  # --- Explore phase ---
  brainstorming:
    source: plugin/superpowers
    phase: explore
    type: phase

  # --- Shape phase ---
  shaping:
    source: vendor/shaping-skills
    phase: shape
    type: phase

  breadboarding:
    source: vendor/shaping-skills
    phase: shape
    type: phase

  # --- Plan phase ---
  writing-plans:
    source: plugin/superpowers
    phase: plan
    type: phase

  # --- Build phase ---
  test-driven-development:
    source: plugin/superpowers
    phase: build
    type: phase

  systematic-debugging:
    source: plugin/superpowers
    phase: build
    type: phase

  # --- Verify phase ---
  verification-before-completion:
    source: plugin/superpowers
    phase: verify
    type: phase

  ui-val:
    source: external
    phase: verify
    type: modifier
    triggers:
      files-changed:
        - "*.tsx"
        - "*.css"
        - "*.html"
        - "*.vue"
        - "*.svelte"

  # --- Review phase ---
  review-loop:
    source: vendor/review-loop
    phase: review
    type: phase

  requesting-code-review:
    source: plugin/superpowers
    phase: review
    type: phase

  # --- Finish phase ---
  finishing-a-development-branch:
    source: plugin/superpowers
    phase: finish
    type: phase

always-available:
  - think-different
  - learning
  - dispatching-parallel-agents
  - subagent-driven-development
  - using-git-worktrees
  - executing-plans
  - receiving-code-review
  - writing-skills

pipelines:
  small-fix:
    description: Bug fix or small tweak with clear approach
    phases: [build, verify, finish]
    skills:
      build:
        - systematic-debugging
        - test-driven-development
      verify:
        - verification-before-completion
      finish:
        - finishing-a-development-branch

  feature:
    description: New feature with clear requirements
    phases: [explore, plan, build, verify, review, finish]
    skills:
      explore:
        - brainstorming
      plan:
        - writing-plans
      build:
        - test-driven-development
      verify:
        - verification-before-completion
      review:
        - requesting-code-review
      finish:
        - finishing-a-development-branch

  complex:
    description: Multi-approach problem, 0-to-1, or significant architectural work
    phases: [explore, shape, plan, build, verify, review, finish]
    skills:
      explore:
        - brainstorming
      shape:
        - shaping
        - breadboarding
      plan:
        - writing-plans
      build:
        - test-driven-development
      verify:
        - verification-before-completion
      review:
        - review-loop
      finish:
        - finishing-a-development-branch
